// Test-only public fixture adapter. No browser global, customer fixture rewrite,
// network, provider call, generation or approval operation occurs here.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';

export const PUBLIC_PRODUCTS = Object.freeze({
  os:'operational_systems', dv:'decision_velocity', sc:'structural_clarity',
  ip:'institutional_performance', depth:'depth_synthesis', synthesis:'cross_lens_synthesis',
});
const sha = value => createHash('sha256').update(value).digest('hex');
const canonical = value => Array.isArray(value) ? value.map(canonical) :
  value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(key => [key,canonical(value[key])])) : value;
export const evidenceDigest = value => sha(JSON.stringify(canonical(value)));
const validHash = value => typeof value === 'string' && /^[a-f0-9]{64}$/.test(value);
const validTime = value => typeof value === 'string' && Number.isFinite(Date.parse(value));
const plain = value => value && typeof value === 'object' && !Array.isArray(value);
export const publicResult = entry => entry.kind === 'diagnostic' && entry.source?.result?.tool_type ? entry.source.result : entry.source;
const DEFAULT_ROOT = fileURLToPath(new URL('../',import.meta.url));
const REQUIRED_SOURCE_FILES = [
  'monderman-report.js','public-sample-model.js','sample-report-production.js',
  'scripts/refresh_public_sample_previews.mjs','scripts/templates/home-workspace-preview.html',
];

// The independent review manifest is a release input, never regenerated by a
// validator. approved_output_sha256 refers to the unstripped private approved
// report; public_source_sha256 binds the deliberately stripped public source.
export function readPublicSampleFixture({root=DEFAULT_ROOT,manifestPath=process.env.PUBLIC_SAMPLE_APPROVAL_MANIFEST}={}) {
  root=path.resolve(root);
  const artifactBytes=fs.readFileSync(path.join(root,'sample-data/production-diagnostic-samples.json'));
  const artifact=JSON.parse(artifactBytes);
  const manifest=JSON.parse(fs.readFileSync(manifestPath ? path.resolve(root,manifestPath) : path.join(root,'sample-data/production-sample-release.json'),'utf8'));
  assert.equal(manifest.contract,'monderman-public-sample-release/v1','reviewed public release manifest missing');
  assert.equal(manifest.status,'reviewed','public content has not completed fidelity review');
  assert.equal(manifest.fidelity_review,'passed','actual six-output fidelity review is required');
  assert.equal(manifest.review_basis,'independent_source_replay_and_visual_review');
  assert.equal(manifest.reviewed_by,'Codex','review must not be attributed to Jason');
  assert.ok(validTime(manifest.reviewed_at),'actual fidelity-review time is missing');
  assert.ok(validHash(manifest.artifact_file_sha256));
  assert.equal(sha(artifactBytes),manifest.artifact_file_sha256,'public artifact bytes differ from the reviewed release');
  assert.equal(artifact.contract,'monderman-public-product-samples/v2');
  assert.equal(artifact.synthetic,true,'the entire artifact must be explicitly synthetic');
  assert.ok(!/dry|pending|not_for_publication|candidate/i.test(artifact.status||''),'unapproved intermediate artifact');
  assert.ok(validHash(artifact.artifact_sha256));
  assert.equal(artifact.artifact_sha256,manifest.artifact_sha256);
  assert.equal(artifact.artifact_digest_basis,'sha256-canonical-json-excluding-artifact_sha256');
  const digestContent={...artifact};delete digestContent.artifact_sha256;
  assert.equal(evidenceDigest(digestContent),artifact.artifact_sha256,'sample content digest is not the completed artifact');
  assert.match(artifact.engine_commit||'',/^[a-f0-9]{40}$/);
  assert.equal(artifact.engine_commit,manifest.engine_commit);
  assert.ok(validTime(artifact.generated_at));
  assert.equal(artifact.generated_at,manifest.generated_at);
  assert.equal(artifact.publication_projection?.version,'monderman-public-sample-projection-20260911.2');
  assert.ok(validHash(artifact.publication_projection.source_sha256));
  assert.match(artifact.publication_projection.projection_commit,/^[a-f0-9]{40}$/);
  assert.deepEqual(artifact.publication_projection,manifest.publication_projection,'publication projection differs from reviewed export');
  const keys=Object.values(PUBLIC_PRODUCTS).sort();
  assert.deepEqual(Object.keys(artifact.outputs||{}).sort(),keys,'exactly six current public products required');
  assert.deepEqual(Object.keys(manifest.outputs||{}).sort(),keys,'all six approved output pins required');
  for(const filename of REQUIRED_SOURCE_FILES) {
    assert.ok(validHash(manifest.source_files?.[filename]),'missing reviewed source pin: '+filename);
    assert.equal(sha(fs.readFileSync(path.join(root,filename))),manifest.source_files[filename],'reviewed source changed: '+filename);
  }
  const entries=[],runs={};
  for(const [tab,key] of Object.entries(PUBLIC_PRODUCTS)) {
    const entry=artifact.outputs[key],pin=manifest.outputs[key],p=entry.provenance,r=publicResult(entry);
    const synthesis=key.endsWith('_synthesis');
    assert.equal(entry.kind,synthesis?'synthesis':'diagnostic',key+' kind');
    assert.ok(plain(entry.source)&&plain(p)&&plain(pin),key+' source, provenance and approval required');
    assert.equal(synthesis?r.synthesis_product:r.tool_type,key,key+' identity');
    assert.equal(p.synthetic,true,key+' synthetic origin');
    assert.ok(validTime(p.generated_at),key+' original sample time');
    for(const name of ['input_sha256','result_sha256','source_manifest_sha256','approved_output_sha256','approved_review_sha256','public_source_sha256']) {
      assert.ok(validHash(p[name]),key+' missing '+name);
    }
    assert.deepEqual(p,pin.provenance,key+' provenance differs from the reviewed receipt');
    assert.equal(evidenceDigest(entry.source),p.public_source_sha256,key+' public projection changed');
    assert.equal(p.ai_status,'complete',key+' missing completed AI provenance');
    const ai=r.ai_report,report=ai?.report;
    assert.equal(ai?.status,'complete',key+' must carry the accepted AI interpretation');
    assert.ok(plain(report?.interpretation),key+' interpretation missing');
    assert.ok(typeof report.interpretation.summary==='string'&&report.interpretation.summary.trim(),key+' empty interpretation');
    assert.ok(report.interpretation.recommendations?.some(row=>typeof row?.action==='string'&&row.action.trim()),key+' accepted next step missing');
    assert.ok(validTime(report.generated_at),key+' AI preparation time missing');
    assert.ok(report.model&&report.prompt_version&&report.version&&report.snapshot_id,key+' AI provenance missing');
    assert.deepEqual({
      model:report.model,generated_at:report.generated_at,prompt_version:report.prompt_version,
      version:report.version,snapshot_id:report.snapshot_id,
    },pin.ai,key+' AI source differs from approved output');
    assert.equal(report.prompt_version,p.report_ai_prompt_version,key+' AI prompt provenance mismatch');
    if(synthesis) {
      assert.equal(r.evidence_assessment?.time_window?.maximum_days,undefined,key+' private qualification limit must not be published');
      assert.equal(r.narrative?.sequenced_action_logic,undefined,key+' internal sequencing duplicate must not be published');
      assert.equal(r.narrative?.what_would_strengthen_the_read,undefined,key+' private next-band target must not be published');
      assert.ok(!(r.priority_actions||[]).some(row=>row.source==='evidence_requirement'),key+' private qualification targets must not be published');
      assert.ok(Number.isInteger(r.submitted_run_count)&&r.submitted_run_count>0,key+' submitted-run count');
      assert.equal(r.submitted_run_count,p.submitted_run_count,key+' count differs from source ledger');
      assert.equal(r.respondent_count,null,key+' must not invent distinct people');
      assert.equal(r.participant_count,null,key+' must not invent distinct participants');
      const exposure=r.pathway_exposure||r.compounded_exposure;
      if(['available','partial'].includes(exposure?.status)) {
        assert.equal(exposure.not_compounded,true,key+' overlapping exposure must not be summed');
        assert.ok(exposure.priceable_runs<=exposure.total_runs);
      }
    } else {
      assert.ok(Number.isFinite(r.score)&&r.score>=0&&r.score<=100,key+' score missing');
      assert.ok(plain(r.dimensions)&&Object.keys(r.dimensions).length>0,key+' dimensions missing');
      assert.ok(r.questionnaire_version&&r.scorer_version,key+' calculation provenance missing');
      runs[key]=entry.source;
    }
    entries.push({tab,key,kind:entry.kind,source:entry.source,provenance:p,result:r});
  }
  return {artifact,manifest,entries,runs,fixtures:{
    crossLens:artifact.outputs.cross_lens_synthesis.source,
    depth:artifact.outputs.depth_synthesis.source,
  }};
}

// Uses the same small adapter as the production page, preserving provenance in
// exports. Existing synthetic pending/empty/hostile fixtures remain independent.
export function createPublicSampleModels(options={}) {
  const fixture=readPublicSampleFixture(options);
  const root=path.resolve(options.root||DEFAULT_ROOT);
  const context={window:{},console,Intl,Date,Number,String,Array,Object,Math,JSON,WeakSet,Blob,URL,setTimeout,clearTimeout};
  vm.createContext(context);
  vm.runInContext(fs.readFileSync(path.join(root,'monderman-report.js'),'utf8'),context,{filename:'monderman-report.js'});
  vm.runInContext(fs.readFileSync(path.join(root,'public-sample-model.js'),'utf8'),context,{filename:'public-sample-model.js'});
  const Report=context.window.MondermanReport,Public=context.window.MondermanPublicSamples;
  assert.equal(Report.rendererVersion,'diagnostic-renderer-ai-screen-20260911.25');
  assert.equal(Report.rendererVersion,fixture.manifest.renderer_version);
  Public.validate(fixture.artifact);
  const models={};
  for(const entry of fixture.entries) {
    const before=JSON.stringify(fixture.artifact.outputs[entry.key]);
    const model=Public.model(fixture.artifact.outputs[entry.key],fixture.artifact);
    assert.equal(JSON.stringify(fixture.artifact.outputs[entry.key]),before,entry.key+' model adapter mutated saved source');
    assert.equal(model.aiReport.status,'complete');
    assert.equal(JSON.stringify(model.aiReport),JSON.stringify(entry.result.ai_report),entry.key+' accepted AI state changed in model adapter');
    assert.equal(model.sampleProvenance.generated_at,entry.provenance.generated_at);
    assert.equal(model.sampleProvenance.approved_output_sha256,entry.provenance.approved_output_sha256);
    assert.ok(model.meta.some(row=>row.label==='Sample created'));
    assert.ok(!model.meta.some(row=>row.label==='Generated'),'view time must not replace sample generation time');
    models[entry.key]=model;
  }
  return {...fixture,Report,Public,models};
}

if(process.argv[1]&&fs.realpathSync(process.argv[1])===fs.realpathSync(fileURLToPath(import.meta.url))) {
  const args=process.argv.slice(2),rootAt=args.indexOf('--root');
  assert.ok(args.includes('--check'),'read-only --check is required');
  const {artifact,entries}=createPublicSampleModels({root:rootAt>=0?args[rootAt+1]:DEFAULT_ROOT});
  console.log(JSON.stringify({passed:true,products:entries.length,engine_commit:artifact.engine_commit,artifact_sha256:artifact.artifact_sha256,networkRequests:0,providerCalls:0}));
}
