// Exact saved planning cases through the real/sample shared renderer.
// Local transports only; no provider, customer or publication writes.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {sourceBeforeSankeyPresentation,restoreSankeyPresentationStyles,PRIOR_SANKEY_RENDERER_SHA256} from './report_sankey_presentation_inverse.mjs';
const root=path.resolve(import.meta.dirname,'..'),source=fs.readFileSync(path.join(root,'monderman-report.js'),'utf8');
const fixtureSource=fs.readFileSync(path.join(root,'sample-data/production-diagnostic-samples.json'),'utf8'),artifact=JSON.parse(fixtureSource),clone=structuredClone;
const context={window:{},console,Intl,Date,Number,String,Array,Object,Math,JSON,WeakSet,Blob,URL,setTimeout,clearTimeout};
for(const file of ['participant-evidence-safety.js','monderman-report.js','public-sample-model.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),context);
const report=context.window.MondermanReport;
let checks=0;const ok=(v,label)=>{assert.ok(v,label);checks++;},eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;},sha=v=>createHash('sha256').update(v).digest('hex');
const priorSource=sourceBeforeSankeyPresentation(source),priorContext={...context,window:{}};
eq(sha(priorSource),PRIOR_SANKEY_RENDERER_SHA256,'Exact historical source recovered');
for(const text of [fs.readFileSync(path.join(root,'participant-evidence-safety.js'),'utf8'),priorSource,fs.readFileSync(path.join(root,'public-sample-model.js'),'utf8')])vm.runInNewContext(text,priorContext);
for(const mutate of [s=>s+'\nUNREVIEWED',s=>s.replace('scopeConfirmed!==true','scopeConfirmed===true'),s=>s.replace('item.amount/sum*hubHeight','item.amount/maxFlow*hubHeight')]){const changed=mutate(source);ok(changed!==source,'Negative control really changes source');assert.throws(()=>sourceBeforeSankeyPresentation(changed));checks++;}
const caption='Directional estimates based on reported operating data and the assumptions shown. Figures indicate potential time and capacity gains, not measured savings.';
const figure=html=>html.match(/<figure class="mr-operational-sankey"[\s\S]*?<\/figure>/)?.[0]||'';
const levels=['low','central','high'],costLevel={low:'high',central:'central',high:'low'},title=k=>k[0].toUpperCase()+k.slice(1);
const metrics=['potentialHoursFreed','capacityValue','avoidableNonLaborCash','cashInvestment','totalImplementationAndSubscriptionCost','netCashEffect','netCapacityAndCashValue'];
const number=v=>Number(v).toLocaleString('en-US',Math.abs(v)>0&&Math.abs(v)<1?{maximumSignificantDigits:3}:{maximumFractionDigits:0});
const format=(key,v)=>key==='potentialHoursFreed'?number(v):(v<0?'-$':'$')+number(Math.abs(v));
const value=(s,key,level)=>s.totals[key][['cashInvestment','totalImplementationAndSubscriptionCost'].includes(key)?costLevel[level]:level];
const build=raw=>{const before=JSON.stringify(raw),model=report.fromSynthesis(raw),html=report.buildReportHtml(model);eq(JSON.stringify(raw),before,'Source unchanged');return {raw,model,html};};
const cases=['depth_synthesis','cross_lens_synthesis'].flatMap(key=>[false,true].map(sample=>{if(!sample)return {key,sample,...build(clone(artifact.outputs[key].source))};const model=context.window.MondermanPublicSamples.model(artifact.outputs[key],artifact);return {key,sample,raw:artifact.outputs[key].source,model,html:report.buildReportHtml(model)};}));
for(const item of cases){
  const chart=figure(item.html),s=item.raw.financial_scenario;ok(chart,'Chart present');ok(chart.includes(caption),'Approved caption');eq(chart.includes('Illustrative example.'),item.sample,'Illustrative only for sample');eq((chart.match(/type="radio"/g)||[]).length,3,'Three native controls');ok(chart.includes('value="central" checked'),'Central default');ok(chart.includes('planning-value comparison, not cash flow'),'Capacity is not cash');ok(chart.includes('Value shortfall')&&chart.includes('not a benefit or funding'),'Negative low case honest');ok(!chart.includes('data-sankey-hours'),'No mixed units');ok(!/Productive effort|Structural overhead|Recoverable burden/.test(chart),'No old score-derived semantics');
  for(const key of metrics)for(const level of levels){const saved=value(s,key,level),match=chart.match(new RegExp('data-planning-metric="'+key+'" data-planning-case="'+level+'" data-saved-value="([^"]+)">([^<]+)'));ok(match,'All seven metrics');eq(Number(match[1]),saved,'Exact saved value');eq(match[2],format(key,saved),'Exact table rounding and cost pairing');}
  const prior=priorContext.window.MondermanReport,model=item.sample?priorContext.window.MondermanPublicSamples.model(artifact.outputs[item.key],artifact):prior.fromSynthesis(artifact.outputs[item.key].source),old=prior.buildReportHtml(model);
  eq(restoreSankeyPresentationStyles(item.html).replace(chart,''),old,'Entire report outside chart and exact CSS unchanged');ok(item.html.indexOf(chart)<item.html.indexOf('class="mr-section mr-ai-interpretation'),'Near top before interpretation');const table=h=>h.match(/<table class="mr-financial-comparison">[\s\S]*?<\/table>/)[0];eq(table(item.html),table(old),'Comparison table byte-identical');
}
const negative=[['no financial data',r=>delete r.financial_scenario],['wrong scope',r=>r.financial_scenario.scope.scopeId='other'],['self run',r=>{r.source_mode='own_saved_runs';r.report_kind='self_run_synthesis';}],['scores used',r=>r.financial_scenario.method.usesDiagnosticScores=true],['overlap not reviewed',r=>r.financial_scenario.inputs.overlapReviewed=false],['duplicate activity',r=>r.financial_scenario.activities[1]=clone(r.financial_scenario.activities[0])],['missing activity',r=>r.financial_scenario.activities.pop()],['unknown activity',r=>r.financial_scenario.activities[0].id='unknown'],['missing range',r=>delete r.financial_scenario.activities[0].potentialHoursFreed],['mismatched hours',r=>r.financial_scenario.activities[0].potentialHoursFreed.central+=100],['mismatched capacity',r=>r.financial_scenario.activities[0].capacityValue.central+=100],['null activity',r=>r.financial_scenario.activities[0]=null],['negative hours',r=>r.financial_scenario.activities[0].potentialHoursFreed.low=-1],['NaN hours',r=>r.financial_scenario.activities[0].potentialHoursFreed.central=NaN],['unordered range',r=>r.financial_scenario.activities[0].potentialHoursFreed.high=0],['unbalanced net',r=>r.financial_scenario.totals.netCapacityAndCashValue.central+=1],['unbalanced cash net',r=>r.financial_scenario.totals.netCashEffect.central+=1],['negative cash',r=>r.financial_scenario.totals.avoidableNonLaborCash={low:-1,central:-1,high:-1}],['negative cost',r=>r.financial_scenario.totals.cashInvestment={low:-1,central:-1,high:-1}],['missing activity cash',r=>delete r.financial_scenario.activities[0].avoidableNonLaborCash],['unbalanced cash activity',r=>r.financial_scenario.activities[0].avoidableNonLaborCash.high=100]];
for(const [label,change]of negative){const raw=clone(artifact.outputs.depth_synthesis.source);change(raw);ok(!figure(build(raw).html),'Invalid chart withheld: '+label);}
const missing=clone(artifact.outputs.depth_synthesis.source);missing.financial_scenario.activities.pop();ok(build(missing).html.includes('saved activity breakdown or planning totals are not complete enough'),'Missing chart explained');
for(const key of ['structural_clarity','decision_velocity','operational_systems','institutional_performance'])ok(!figure(report.buildReportHtml(report.fromRun(artifact.outputs[key].source))),'No single-run financial Sankey');
// In-memory synthetic edge cases only, never publication data.
const sumScenario=raw=>{const s=raw.financial_scenario;for(const key of ['potentialHoursFreed','capacityValue','avoidableNonLaborCash'])s.totals[key]=Object.fromEntries(levels.map(k=>[k,s.activities.reduce((n,a)=>n+a[key][k],0)]));for(const level of levels){s.totals.netCapacityAndCashValue[level]=s.totals.capacityValue[level]+s.totals.avoidableNonLaborCash[level]-s.totals.totalImplementationAndSubscriptionCost[costLevel[level]];s.totals.netCashEffect[level]=s.totals.avoidableNonLaborCash[level]-s.totals.cashInvestment[costLevel[level]];}return raw;};
const variant=(key,fn)=>{const raw=clone(artifact.outputs.cross_lens_synthesis.source);fn(raw.financial_scenario);return {key,sample:false,...build(sumScenario(raw))};};
const edgeCases=[variant('zero',s=>{for(const a of s.activities)for(const key of ['potentialHoursFreed','capacityValue','avoidableNonLaborCash'])a[key]={low:0,central:0,high:0};for(const key of ['cashInvestment','totalImplementationAndSubscriptionCost'])s.totals[key]={low:0,central:0,high:0};}),variant('all-shortfall',s=>{for(const a of s.activities)for(const key of ['potentialHoursFreed','capacityValue','avoidableNonLaborCash'])a[key]={low:0,central:0,high:0};}),variant('central-zero-high-positive',s=>{for(const a of s.activities)for(const key of ['potentialHoursFreed','capacityValue'])a[key]={low:0,central:0,high:a[key].high};}),variant('cash-positive',s=>{for(const a of s.activities)a.avoidableNonLaborCash={low:5000,central:10000,high:20000};}),variant('tiny',s=>{for(const a of s.activities)for(const key of ['potentialHoursFreed','capacityValue'])a[key]={low:.0001,central:.002,high:.03};for(const key of ['cashInvestment','totalImplementationAndSubscriptionCost'])s.totals[key]={low:.0001,central:.0002,high:.0003};}),variant('huge',s=>{for(const a of s.activities)for(const key of ['potentialHoursFreed','capacityValue'])a[key]={low:1e13,central:2e13,high:3e13};}),variant('many-activities',s=>{s.inputs.activities=Array.from({length:12},(_,i)=>({...clone(s.inputs.activities[0]),id:'activity-'+i,label:'Distinct operating work '+i}));s.activities=s.inputs.activities.map(a=>({id:a.id,label:a.label,potentialHoursFreed:{low:10,central:20,high:30},capacityValue:{low:100,central:200,high:300},avoidableNonLaborCash:{low:0,central:0,high:0}}));})];
for(const item of edgeCases)ok(figure(item.html),'Valid edge case: '+item.key);eq((figure(edgeCases[0].html).match(/data-sankey-dollars=/g)||[]).length,0,'Zero has no fabricated flow');ok(figure(edgeCases[1].html).includes('data-sankey-node="valueShortfall"'),'All-shortfall explicit');ok(figure(edgeCases.find(x=>x.key==='tiny').html).includes('$0.004'),'Tiny value not zero');
const hostile=clone(artifact.outputs.depth_synthesis.source);hostile.financial_scenario.activities[0].label='<img src=x onerror=alert(1)>';ok(!figure(build(hostile).html).includes('<img'),'Labels safe');const early=clone(artifact.outputs.depth_synthesis.source);early.financial_scenario.kind='early_planning_scenario';const earlyBuilt=build(early);ok(earlyBuilt.html.includes('This scenario does not unlock Synthesis.'),'Early boundary explicit');ok(figure(earlyBuilt.html),'Early scenario displayable');
if(process.argv.includes('--deterministic-only')){console.log(JSON.stringify({status:'PASS',checks,providerCalls:0}));process.exit(0);}
const out=process.env.REPORT_SANKEY_OUT||fs.mkdtempSync('/tmp/report-operational-sankey-');fs.mkdirSync(out,{recursive:true});const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright'),results=[],pdfs=[],errors=[],unexpected=[];
const routes=async page=>{page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const match=/^https:\/\/www\.monderman\.com\/(55|65|75)font\.woff2$/.exec(route.request().url());if(match)return route.fulfill({contentType:'font/woff2',body:fs.readFileSync(path.join(root,match[1]+'font.woff2'))});unexpected.push(route.request().url());return route.abort();});};
for(const [engine,type]of [['chromium',chromium],['webkit',webkit]]){const browser=await type.launch({headless:true});try{
  for(const width of [320,390,834,1440])for(const item of cases){
    const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});await routes(page);await page.setContent(item.html,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);const chart=page.locator('.mr-operational-sankey');eq(await chart.count(),1,'One chart');eq(await page.locator('.mr-financial-brief .mr-operational-sankey').count(),1,'Near-top placement');eq(await page.locator('.mr-financial-scenario .mr-operational-sankey').count(),0,'Old chart removed');eq(await chart.locator('.mr-planning-panel:visible').getAttribute('data-planning-panel'),'central','Default central visible');
    for(const level of levels){await chart.locator('label').filter({hasText:new RegExp('^'+title(level)+'$')}).click();const panel=chart.locator('[data-planning-panel="'+level+'"]');ok(await panel.isVisible(),'Selected panel visible');eq(await chart.locator('.mr-planning-panel:visible').count(),1,'One screen case');for(const key of metrics){const displayed=panel.locator('[data-planning-metric="'+key+'"]'),table=page.locator('[data-financial-metric="'+key+'"][data-financial-case="'+level+'"]');eq(await displayed.textContent(),await table.textContent(),'Visible metric equals table');eq(Number(await displayed.getAttribute('data-saved-value')),value(item.raw.financial_scenario,key,level),'Exact source value');}ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No viewport overflow');ok(await chart.locator('p,h3,h4,dt,dd,label,.mr-planning-node').evaluateAll(nodes=>nodes.every(el=>{const r=el.getBoundingClientRect();return !r.width||(r.left>=-1&&r.right<=innerWidth+1);} )),'All content contained');const shot=engine+'-'+width+'-'+item.key+(item.sample?'-sample':'-real')+'-'+level+'.png';await chart.screenshot({path:path.join(out,shot)});results.push({engine,width,key:item.key,sample:item.sample,case:level,screenshot:shot});}
    await chart.getByLabel('Central',{exact:true}).focus();await page.keyboard.press('ArrowLeft');eq(await chart.locator('.mr-planning-choice:checked').inputValue(),'low','Native ArrowLeft');await page.keyboard.press('ArrowRight');eq(await chart.locator('.mr-planning-choice:checked').inputValue(),'central','Native ArrowRight');eq(await page.evaluate(()=>document.activeElement?.value),'central','Focus retained');eq(await chart.locator('figcaption').innerText(),(item.sample?'Illustrative example. ':'')+caption,'Exact visible caption');await page.emulateMedia({media:'print'});eq(await chart.locator('.mr-planning-panel:visible').count(),3,'Print all three');eq(await chart.locator('label:visible').count(),0,'No print-only controls');
    if(process.argv.includes('--print')&&engine==='chromium'&&width===1440&&item.sample){const file=path.join(out,item.key+'.pdf');await page.pdf({path:file,printBackground:true,preferCSSPageSize:true});const pages=JSON.parse(execFileSync(process.env.PDF_PYTHON||'python3',['-c','import json,sys;from pypdf import PdfReader;print(json.dumps([p.extract_text() for p in PdfReader(sys.argv[1]).pages]))',file],{encoding:'utf8'})),compact=t=>t.replace(/\s+/g,'');ok(pages[1].includes('Decision brief')&&pages[1].includes('Three planning cases'),'PDF page2 summary');ok(pages[1].includes('Exact values, activity records and assumptions'),'Complete page2 notes');const casePages=[];for(const level of levels){const found=pages.map((text,i)=>({text:compact(text),page:i+1})).filter(p=>p.text.includes(compact(title(level)+' planning case')));eq(found.length,1,'One PDF case heading');ok(found[0].text.includes(compact(caption)),'Caption on case page');for(const key of metrics)ok(found[0].text.includes(compact(format(key,value(item.raw.financial_scenario,key,level)))),'Exact metric on case page');casePages.push(found[0].page);execFileSync(process.env.PDFTOPPM||'pdftoppm',['-f',String(found[0].page),'-l',String(found[0].page),'-scale-to','1400','-png','-singlefile',file,path.join(out,item.key+'-'+level)]);}eq(new Set(casePages).size,3,'Three self-contained PDF pages');pdfs.push({file,pages:pages.length,casePages,sha256:sha(fs.readFileSync(file))});}
    await page.close();
  }
  const multi=await browser.newPage({viewport:{width:390,height:1000}});await routes(multi);await multi.setContent('<main id="reports"></main>');await multi.addScriptTag({content:source});const allModels=Object.entries(artifact.outputs).map(([key,output])=>['depth_synthesis','cross_lens_synthesis'].includes(key)?report.fromSynthesis(output.source):report.fromRun(output.source));await multi.evaluate(models=>{for(const model of models){const host=document.createElement('div');document.querySelector('#reports').append(host);window.MondermanReport.render(host,model);}},[...allModels,cases[0].model,cases[0].model]);ok(await multi.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return new Set(ids).size===ids.length;}),'All co-mounted IDs unique');const charts=multi.locator('.mr-operational-sankey');eq(await charts.count(),4,'Both samples and repeated report');for(let i=0;i<4;i++){const c=charts.nth(i);await c.locator('label').filter({hasText:/^Low$/}).click();for(let j=i+1;j<4;j++)eq(await charts.nth(j).locator('.mr-planning-choice:checked').inputValue(),'central','Radio groups independent');ok(await c.locator('.mr-planning-panel:visible').evaluate(el=>document.getElementById(el.getAttribute('aria-labelledby'))?.textContent==='Low planning case'),'ARIA heading targets correct report');}await multi.close();
  const noscript=await browser.newPage({viewport:{width:390,height:1000},javaScriptEnabled:false});await routes(noscript);await noscript.setContent(cases[0].html);await noscript.locator('.mr-operational-sankey label').filter({hasText:/^High$/}).click();ok(await noscript.locator('[data-planning-panel="high"]').isVisible(),'No-JS High control works');await noscript.close();
  for(const item of edgeCases)for(const width of [320,1440]){const page=await browser.newPage({viewport:{width,height:1000}});await routes(page);await page.setContent(item.html);for(const level of levels){await page.locator('.mr-operational-sankey label').filter({hasText:new RegExp('^'+title(level)+'$')}).click();ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Edge case contained: '+item.key);ok(await page.locator('.mr-operational-sankey svg path').evaluateAll(nodes=>nodes.every(el=>!/(?:NaN|Infinity)/.test(el.getAttribute('d')))),'Finite flow coordinates');}await page.locator('.mr-operational-sankey').screenshot({path:path.join(out,engine+'-'+width+'-'+item.key+'.png')});await page.close();}
}finally{await browser.close();}}
eq(errors,[],'No browser errors');eq(unexpected,[],'No service calls');eq(fs.readFileSync(path.join(root,'sample-data/production-diagnostic-samples.json'),'utf8'),fixtureSource,'Publication inputs unchanged');eq(fs.readFileSync(path.join(root,'monderman-report.js'),'utf8'),source,'Renderer stable during test');fs.writeFileSync(path.join(out,'RECEIPT.json'),JSON.stringify({status:'PASS',checks,results,pdfs,rendererSha256:sha(source),sourceSha256:sha(fixtureSource),providerCalls:0,productionCalls:0},null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks,states:results.length,pdfs:pdfs.length,out}));
