import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'), baseline='f91fb07fde754dea57360ddbddc9bf742d6e6702';
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const prior=f=>execFileSync('git',['show',`${baseline}:${f}`],{cwd:root,encoding:'utf8'});
const inline=html=>[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
assert.ok(read('index.html').includes('<h1 class="hero-title" id="hero-title">Less bureaucracy. Better performance.</h1>'));
assert.ok(read('index.html').includes('"slogan": "Less bureaucracy. Better performance."'));
assert.ok(read('Monderman_Platform_Brief.html').includes('Examine operating conditions. Save the results. Compare them later.'));
for(const f of ['decision-velocity.html','structural-clarity.html','operational-systems.html','institutional-performance.html','accept-invite.html','workspace.html','workspace-diagnostics.html']) assert.deepEqual(inline(read(f)),inline(prior(f)),f+': embedded behavior remains byte-identical');
for(const f of ['privacy.html','terms.html','monderman-report.js','public-sample-model.js','sample-report-production.js','campaign-analysis.js','run-inclusion-review.js','participant-evidence-safety.js','sample-data/production-diagnostic-samples.json'])assert.equal(read(f),prior(f),f+': policy, engine, report or evidence data unchanged');
assert.equal(read('workspace-assistant.js'),prior('workspace-assistant.js').replaceAll('font-family:"Inter",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif','font-family:"Neue Haas Grotesk","Helvetica Neue",Helvetica,Arial,sans-serif'),'Hans changes are font declarations only');
assert.deepEqual(inline(read('signin.html')),inline(prior('signin.html')).map(s=>s.replaceAll('Terms of Service','Terms of Use')),'Sign-in behavior changes are policy display labels only');
const price=read('platform-services.html');
assert.equal((price.match(/href="signin.html\?next=workspace.html">Create a free account/g)||[]).length,2);
assert.equal((price.match(/<tr><td class="rowlabel">New Depth or Cross-Lens Syntheses per annual term, shared allowance<\/td><td class="num">1 total<\/td><td class="num">60<\/td><td class="num">300<\/td><td class="yes">Unlimited<\/td><\/tr>/g)||[]).length,1);
assert.ok(!price.includes('60 / year')&&!price.includes('300 / year'),'No duplicated allowance pool');
assert.ok(price.includes('unlimited self-runs for authorized Workspace users'));
const catalog=read('diagnostics.html');
assert.equal((catalog.match(/class="dx-card-time">10, 30, or 60 minutes/g)||[]).length,4);
assert.ok(catalog.includes('Participation is counted separately for each diagnostic. Each person counts once, even if they complete that diagnostic more than once.'));
const details=catalog.match(/<details class="dx-method-detail">([\s\S]*?)<\/details>/)?.[1];
assert.ok(details?.includes('Independent statistical review: <strong>not reviewed</strong>'));
assert.ok(details.includes('same instrument score band')&&details.includes('not forecasts or measured savings'));
assert.ok(!read('decision-velocity.html').match(/<meta[^>]*what delay costs/));
assert.ok(!read('canonical-site-shell.js').includes('copy.textContent ='));
assert.ok(!read('signin.html').includes('#26496f'));
assert.ok(!read('workspace.html').includes('fonts.googleapis.com'));
const faces=[...read('brand-fonts.css').matchAll(/@font-face\{([^}]+)\}/g)].map(m=>m[1]);
for(const style of ['normal','italic']) for(const weight of [400,500,600,700]) {
  const matches=faces.filter(face=>face.includes(`font-style:${style};`)&&face.includes(`font-weight:${weight};`));
  assert.equal(matches.length,1,`${style} ${weight}: shared font mapping must be a single discrete face`);
  const file=(style==='italic'?{400:'56',500:'66',600:'66',700:'76'}:{400:'55',500:'65',600:'65',700:'75'})[weight];
  assert.ok(matches[0].includes(`url("${file}font.woff2")`));
}
assert.ok(read('accept-invite.html').includes('class="invitation-brand"')&&!read('accept-invite.html').includes('&#9679;'));
console.log('PASS approved site consistency: exact copy, shared allowances, technical details, immutable policies and unchanged diagnostic/report logic.');
