from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "plan-pattern.html"
s = path.read_text(encoding="utf-8")
old = '''        <div class="pl-buy">\n          <a class="btn btn-accent" href="checkout.html?tier=pattern&amp;interval=monthly">Monthly &mdash; $3,000/mo</a>\n          <a class="btn btn-accent" href="checkout.html?tier=pattern&amp;interval=quarterly">Quarterly &mdash; $2,850/mo <span>save 5% &middot; one measurement cycle</span></a>\n          <a class="btn btn-accent" href="checkout.html?tier=pattern&amp;interval=annual">Annual &mdash; $2,550/mo <span>save 15%</span></a>\n        </div>\n        <p class="pl-note">Secure card checkout by <strong>Stripe</strong>; card details never touch Monderman. Sign-in required, and the tier unlocks for your whole workspace. Renews automatically; cancel any time, effective end of the paid period. Prefer invoicing on a purchase order? <a href="connect.html?plan=signal" style="color:var(--accent);font-weight:600">Request an order form</a> instead.</p>\n      </div>\n      <style>.pl-buy{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0 6px;}.pl-buy .btn{display:block;text-align:center;padding:14px 10px;font-size:14.5px;text-decoration:none;}.pl-buy .btn span{display:block;font-size:11.5px;font-weight:500;opacity:.85;margin-top:3px;}@media(max-width:700px){.pl-buy{grid-template-columns:1fr;}}</style>\n'''
new = '''        <div class="pl-trial-offer">\n          <div>\n            <strong>Evaluate Pattern for 30 days.</strong>\n            <span>Full Pattern Workspace access. No card required. One trial per Workspace, and it does not renew automatically.</span>\n          </div>\n          <a class="btn btn-accent" href="pattern-trial.html">Start free 30-day trial</a>\n        </div>\n        <div class="pl-buy">\n          <a class="btn btn-accent" href="checkout.html?tier=pattern&amp;interval=monthly">Monthly &mdash; $3,000/mo</a>\n          <a class="btn btn-accent" href="checkout.html?tier=pattern&amp;interval=quarterly">Quarterly &mdash; $2,850/mo <span>save 5% &middot; one measurement cycle</span></a>\n          <a class="btn btn-accent" href="checkout.html?tier=pattern&amp;interval=annual">Annual &mdash; $2,550/mo <span>save 15%</span></a>\n        </div>\n        <p class="pl-note">Secure card checkout by <strong>Stripe</strong>; card details never touch Monderman. Sign-in required, and the tier unlocks for your whole workspace. Paid subscriptions renew automatically; cancel any time, effective end of the paid period. Prefer invoicing on a purchase order? <a href="connect.html?plan=pattern" style="color:var(--accent);font-weight:600">Request an order form</a> instead.</p>\n      </div>\n      <style>.pl-trial-offer{display:flex;align-items:center;justify-content:space-between;gap:22px;margin:18px 0 22px;padding:20px 22px;border:1px solid rgba(12,110,120,.28);border-radius:12px;background:rgba(12,110,120,.07)}.pl-trial-offer strong{display:block;font-size:1.05rem;color:var(--accent-dark);margin-bottom:5px}.pl-trial-offer span{display:block;max-width:54ch;font-size:.91rem;line-height:1.5;color:var(--muted-dark)}.pl-trial-offer .btn{flex:0 0 auto;min-width:210px}.pl-buy{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0 6px;}.pl-buy .btn{display:block;text-align:center;padding:14px 10px;font-size:14.5px;text-decoration:none;}.pl-buy .btn span{display:block;font-size:11.5px;font-weight:500;opacity:.85;margin-top:3px;}@media(max-width:700px){.pl-trial-offer{align-items:stretch;flex-direction:column}.pl-trial-offer .btn{width:100%}.pl-buy{grid-template-columns:1fr;}}</style>\n'''
count=s.count(old)
if count != 1:
    raise SystemExit(f"Pattern purchase block: expected one match, found {count}")
s=s.replace(old,new,1)
path.write_text(s,encoding="utf-8")
print("Pattern trial offer inserted into Pattern plan page.")
